### ISSUE TITLE
Ask about the Results

### ISSUE THREAD

**Issue by imamnurby** [hapsby/deepAPIRevisited#1]
Hi! I am wondering whether you have done the experiment using CodeBERT on these data?
I am wondering whether you have a plan to release the results and also the model's checkpoint?
It would be great if you plan to do so :)

Thanks!

**Comment by hapsby** [comment]
Hi imamnurby,

Thank you for your interest in this project.  Yes, we have done the experiment in CodeBERT.  The paper pre-print with results is at:  https://arxiv.org/abs/2205.01254

The models and datasets are available at:  https://zenodo.org/record/6388030

The models for deepAPI won't work with the deepAPI project at guxd/deepAPI because the format of the .h5 files is a bit different.  This weekend, I will make a fork of guxd/deepAPI with the necessary modifications.

**Comment by imamnurby** [comment]
> This weekend, I will make a fork of guxd/deepAPI with the necessary modifications.

Thank you! I am looking forward for this! :)

**Comment by hapsby** [comment]
The forks of deepAPI and CodeBERT are now available:

https://github.com/hapsby/deepAPIPython

https://github.com/hapsby/CodeBERT-deepAPI
